from .tokenJWT import *
from .location import *
from .dashboard import *
from .avatars import *
from .drfLogger import *
from .maintenance import *
from .pandrugs import *
from .variant_analysis import *
from .patient import *
from .drug_query import *
from .report import *
