# Generated by Django 5.1 on 2025-09-15 11:17

import random
import string
from django.db import migrations

def generate_default_patient_id():
    # Generate a random 12-character alphanumeric string
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=12))

def backfill_patient_ids(apps, schema_editor):
    Patient = apps.get_model("mmpc", "Patient")

    for patient in Patient.objects.filter(appId__isnull=True):
        new_id = generate_default_patient_id()
        while Patient.objects.filter(appId=new_id).exists():
            new_id = generate_default_patient_id()
        patient.appId = new_id
        patient.save()

def backfill_patient_sex_id(apps, schema_editor):
    Patient = apps.get_model("mmpc", "Patient")
    Sex = apps.get_model("mmpc", "Sex")
    default_sex_id = Sex.objects.get(id = 1)

    for patient in Patient.objects.filter(sex_id__isnull=True):
        patient.sex_id = default_sex_id
        patient.save()

def reverse_operation(apps, schema_editor):
    Patient = apps.get_model('mmpc', 'Patient')
    # Revert the changes if necessary

class Migration(migrations.Migration):

    dependencies = [
        ('mmpc', '0009_alter_studyprodeduretype_type'),
    ]

    operations = [
        migrations.RunPython(backfill_patient_ids, reverse_operation),
        migrations.RunPython(backfill_patient_sex_id, reverse_operation),
    ]
