# Generated by Django 5.1 on 2025-09-15 11:17

import random
import string
from django.db import migrations

def generate_history_id():
    # Generate a random 12-character alphanumeric string
    return 'PH' + ''.join(random.choices(string.digits, k=10))


def backfill_history_ids(apps, schema_editor):
    Report = apps.get_model("mmpc", "Report")

    for report in Report.objects.filter(appId__isnull=True):
        new_id = generate_history_id()
        while Report.objects.filter(appId=new_id).exists():
            new_id = generate_history_id()
        report.appId = new_id
        report.save()

def reverse_operation(apps, schema_editor):
    Report = apps.get_model('mmpc', 'Report')
    # Revert the changes if necessary

class Migration(migrations.Migration):

    dependencies = [
        ('mmpc', '0010_auto_20250915_1317'),
    ]

    operations = [
        migrations.RunPython(backfill_history_ids, reverse_operation),
    ]
