# Generated by Django 5.1 on 2025-03-26 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpc', '0004_drugquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='entityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('codename', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'group Entity',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='custom_identifier',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='variantanalysis',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mmpc.patient'),
            preserve_default=False,
        ),
    ]
