"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from os import environ
from datetime import timedelta
import pytz
from datetime import datetime


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: be careful with these values ​​for production
SECRET_KEY = environ.get('DJANGO_SECRET_KEY')

DEBUG = environ.get('DJANGO_DEBUG') == 'True'

ALLOWED_HOSTS_STR = environ.get('DJANGO_ALLOWED_HOSTS')

if ALLOWED_HOSTS_STR == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ALLOWED_HOSTS_STR.split(',')

CORS_ORIGIN_ALLOW_ALL = environ.get('DJANGO_CORS_ORIGIN_ALLOW_ALL') == 'True'

if not CORS_ORIGIN_ALLOW_ALL:
    CORS_ORIGIN_WHITELIST = environ.get('DJANGO_CORS_ORIGIN_WHITELIST').split(',')

CSRF_TRUSTED_ORIGINS = environ.get('DJANGO_CSRF_TRUSTED_ORIGINS').split(',')


# Increase application security
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_CONTENT_TYPE_OPTIONS = 'nosniff'
X_FRAME_OPTIONS = 'DENY'
X_XSS_PROTECTION = '1; mode=block'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'maintenance_mode',
    'mmpc',
    'drf_api_logger',
    'axes',
    'django_dia',
    'django_apscheduler',
    'dbbackup',
    'channels',
    'channels_redis'
]


APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds


DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': '/api/backups/'}



MIDDLEWARE = [
   
    #'mmpc.middleware.IpFilterMiddleware',
    #'mmpc.middleware.AllowCountryMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
    'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware'
]


AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AXES_RESET_ON_SUCCESS = True
AXES_USERNAME_FORM_FIELD = "email"
AXES_FAILURE_LIMIT = 10
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    'IP_ORIGIN'
]


REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
   ),
   'EXCEPTION_HANDLER': 'axes_banned.jwtTokenException.customExceptionHandler',
   
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(hours=1)

}


CORS_EXPOSE_HEADERS = [
    'Content-Disposition'
]


ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': environ.get('PSQL_NAME'),
        'USER': environ.get('PSQL_USER'),
        'PASSWORD': environ.get('PSQL_PASSWORD'),
        'HOST': environ.get('PSQL_HOST'),
        'PORT': environ.get('PSQL_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REDIS_HOST = environ.get('DJANGO_REDIS_HOST')
REDIS_PORT = environ.get('DJANGO_REDIS_PORT')
REDIS_PASSWORD = environ.get('DJANGO_REDIS_PASSWORD')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}')],
        },
        'MIDDLEWARE': [
            'django_channels_jwt.middleware.JsonWebTokenAuthMiddleware',
        ],
    },
}

CHANNELS_JWT = {
    'SECRET_KEY': SECRET_KEY,
    'ALGORITHM': 'HS256',
    'HEADER': 'authorization'
}

ASGI_APPLICATION = 'api.asgi.application'


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/api/staticfiles/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'mmpc.customUser'

DRF_API_LOGGER_DATABASE = True

# Check auto time for DRF_API_LOGGER (UTC +2 or UTC +1)
def is_dst():
    tz = pytz.timezone('Europe/Madrid')
    now = datetime.now(tz)
    return now.dst() != timedelta(0)

if is_dst():
    DRF_API_LOGGER_TIMEDELTA = 120  # UTC +2
else:
    DRF_API_LOGGER_TIMEDELTA = 60   # UTC +1

#--------MAINTENANCE-MODE---------------
MAINTENANCE_MODE_IGNORE_URLS = ('/maintenance-status',)
# the absolute url where users will be redirected to during maintenance-mode
MAINTENANCE_MODE_REDIRECT_URL = '/maintenance-status/'