FROM nginx:stable

RUN apt-get update && apt-get upgrade -y && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Copy nginx config
COPY ./nginx.conf /etc/nginx/nginx.conf

# Port
EXPOSE 80

# Execute nginx
CMD ["nginx", "-g", "daemon off;"]