# Use the official Redis image
FROM redis:latest

# Install gettext (for envsubst command)
RUN apt-get update && apt-get install -y gettext-base

# Copy configuration files
COPY redis.template.conf /usr/local/etc/redis/redis.template.conf
COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# run
ENTRYPOINT ["entrypoint.sh"]